routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/proselect','HomeController@orgselect')->name('orgselect');
Route::post('/proselect','HomeController@orgselect')->name('orgselect');

Route::resource('users', 'UserController');
// Route::resource('permissions', 'PermissionController');
// Route::resource('roles', 'RoleController');
Route::resource('projects', 'OrganizationController');
Route::group(['middleware' => 'orgSelect'], function () {
	Route::get('/home', 'HomeController@index')->name('home');

	
	Route::resource('floorplans', 'DepartmentController');
	
	Route::get('floorplans/{id}/restore', 'DepartmentController@restore')->name('departments.restore');
	Route::resource('projectresponsibilities', 'EmployeeController');
	Route::get('projectresponsibilities/{id}/restore', 'EmployeeController@restore')->name('employees.restore');
	Route::post( '/getUserDepartments', array('as' => 'getUserDepartments', 'uses' => 'EmployeeController@getUserDepartments'));
	
	Route::post('/getOrgUsers', array('as' => 'getOrgUsers', 'uses'=> 'OrganizationController@getOrgUsers'));
	Route::post('/getDepUsers', array('as' => 'getDepUsers', 'uses'=> 'CalendarController@getDepUsers'));
	
	Route::get('/importUsers','UserController@import')->name('importUsers');
	Route::get('/exportUsers','UserController@export')->name('exportUsers');
	Route::get('/downloadEmployeeCsv', 'UserController@getDownload');
	
	// Route::get('/calendars/{id}/approve', array('as' => 'calendars.approve', 'uses'=> 'CalendarController@approve'));
	// Route::get('/calendars/{id}/reject', array('as' => 'calendars.reject', 'uses'=> 'CalendarController@reject'));
	// Route::get('laborcost', 'CostController@index')->name('laborcost');
	// Route::resource('calendars', 'CalendarController');
	// Route::get('calendars/{id}/restore', 'CalendarController@restore')->name('calendars.restore');
	// Route::get('/importCalendars','CalendarController@import')->name('importCalendars');
	// Route::get('/exportCalendars','CalendarController@exportCalendars')->name('exportCalendars');
	// Route::get('/downloadCalendarCsv', 'CalendarController@getDownload');

	
});

// Route::resource('contactForms', 'ContactFormController');
Route::resource('clientdata', 'OrganizationVendorsController');

app/Models/Employee.php
<?php namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Employee
 * @package App\Models
 * @version November 22, 2018, 12:25 pm UTC
 *
  * @property \Illuminate\Database\Eloquent\Collection calendarUsers
 * @property \Illuminate\Database\Eloquent\Collection DepartmentEmployee
 * @property \Illuminate\Database\Eloquent\Collection organizationUsers
 * @property \Illuminate\Database\Eloquent\Collection roleHasPermissions
 * @property integer user_id
 * @property string department
 * @property float cost

 */
class Employee extends Model {
	    use SoftDeletes;

	public $table = 'employees';
	
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

	
    protected $dates = ['deleted_at'];

	
	public $fillable = [
		'user_id',
		'department_id',
		'cost',
		'avatar',
		'job_title'
	];

	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'id' => 'integer',
		'user_id' => 'integer',
		'department_id' => 'integer',
		'cost' => 'float',
		'avatar' => 'string',
		'job_title' => 'string'

	];

	/**
	 * Validation rules
	 *
	 * @var array
	 */
	public static $rules = [
		'employee.avatar' => 'image',
		'name' => 'required',
		'email' => 'required',
		'employee.department_id' => 'required',
		'employee.job_title' => 'required',
		'employee.cost' => 'required|numeric',

	];

	public function setAvatarAttribute($file) {
		if (is_file($file)) {
			$file = \Storage::put('public/employees', $file, 'public');
		}
		$this->attributes['avatar'] = $file;
	}

	public function getAvatarAttribute($file) {
		if (\Storage::exists($this->attributes['avatar'])) {
			$url = url(\Storage::url($this->attributes['avatar']));
			return $url;
		}
		return $file;
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function department() {
		return $this->belongsTo(\App\Models\Department::class);
	}
	
	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function user() {
		return $this->belongsTo(\App\Models\User::class);
	}
}

app/Http/Controllers/EmployeeController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\CreateEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;
use App\Repositories\EmployeeRepository;
use App\Repositories\OrganizationRepository;
use App\Repositories\UserRepository;
use App\Repositories\RoleRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use \App\Models\Employee;
use \App\Models\User;
use \App\Models\Department;
use \App\Models\Organization;

class EmployeeController extends AppBaseController {
	/** @var  EmployeeRepository */
	private $employeeRepository;
	private $roleRepository;
	private $userRepository;
	private $organizationRepository;

	public function __construct(EmployeeRepository $employeeRepo, RoleRepository $roleRepo, OrganizationRepository $organizationRepo, UserRepository $userRepo) {
		$this->middleware('verified');
		$this->employeeRepository = $employeeRepo;
		$this->userRepository = $userRepo;
		$this->roleRepository = $roleRepo;
		$this->organizationRepository = $organizationRepo;
	}

	/**
	 * Display a listing of the Employee.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function index(Request $request) {
		$organization = $this->organizationRepository->find(session()->get('organization_id'));
		if($request->has('trashed')) {
			$users = $organization->users()->onlyTrashed()->paginate(10);
		} else {
			$users = $organization->users()->paginate(10) ;
		}
		return view('employees.index')
			->with('users', $users);
	}

	/**
	 * Show the form for creating a new Employee.
	 *
	 * @return Response
	 */
	public function create() {
		$organization = $this->organizationRepository->find(session()->get('organization_id'));
		$roles = $this->roleRepository->findWhereIn('name', ['orgadmin', 'orguser'])->pluck('name', 'id');
		$departments = $organization->departments()->pluck('name', 'id');
		return view('employees.create')
					->with('roles', $roles)
					->with('departments', $departments);
	}

	/**
	 * Store a newly created Employee in storage.
	 *
	 * @param CreateEmployeeRequest $request
	 *
	 * @return Response
	 */
	public function store(CreateEmployeeRequest $request) {
		$input = $request->except('organization');

		$input['organizations'] = [[
			'organization_id' => session()->get('organization_id'),
			'role_id' => $request->get('organization')['pivot']['role_id']
		]];
		$input['password'] = str_random(16);

		$user = $this->userRepository->create($input);
		$input['employee']['user_id'] = $user->id;
		$employee = $this->employeeRepository->create($input['employee']);

		Flash::success('Employee saved successfully.');

		return redirect(route('projectresponsibilities.index'));
	}

	/**
	 * Display the specified Employee.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id) {
		$user = $this->userRepository->findWithoutFail($id);
		if (empty($user)) {
			Flash::error('User not found');
			return redirect(route('projectresponsibilities.index'));
		}
		return view('employees.show')->with('user', $user);
	}

	/**
	 * Show the form for editing the specified Employee.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id) {
		$user = $this->userRepository->findWithoutFail($id)->load('organizations', 'employee.department.organization');
		$org_id = session()->get('organization_id');
		$user->organization = $user->organizations->where('id', '=', $org_id)->first();
		$roles = $this->roleRepository->findWhereIn('name', ['orgadmin', 'orguser'])->pluck('name', 'id');
		$departments = $user->organization->departments()->pluck('name', 'id');

		if (empty($user)) {
			Flash::error('User not found');
			return redirect(route('projectresponsibilities.index'));
		}

		return view('employees.edit')
					->with('user', $user)
					->with('roles', $roles)
					->with('departments', $departments);
		}

	/**
	 * Update the specified Employee in storage.
	 *
	 * @param  int			  $id
	 * @param UpdateEmployeeRequest $request
	 *
	 * @return Response
	 */
	public function update($id, UpdateEmployeeRequest $request) {
		$user = $this->userRepository->findWithoutFail($id);
		$input = $request->except('employee');
		$input['organizations'] = [[
			'organization_id' => session()->get('organization_id'),
			'role_id' => $request->get('organization')['pivot']['role_id']
		]];

		$employee = null;
		if($user->employee) {
			$employee = $this->employeeRepository->find($user->employee->id);
		}
		$employee_input = $request->all()['employee'];

		if (empty($user)) {
			Flash::error('User not found');
			return redirect(route('projectresponsibilities.index'));
		}

		$user = $this->userRepository->update($input, $id);
		if($employee) {
			$employee = $this->employeeRepository->update($employee_input, $employee->id);
		} else {
			$employee = $user->employee()->create($employee_input);
		}
		Flash::success('Employee updated successfully.');

		return redirect(route('projectresponsibilities.index'));
	}

	/**
	 * Restore the specified Employee from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function restore($id) {
		$user = \App\Models\User::withTrashed()->find($id);
		
		if (empty($user)) {
			Flash::error('User not found');
			return redirect(route('projectresponsibilities.index'));
		}

		$user->restore();

		Flash::success('Employee restored successfully.');
		return redirect(route('projectresponsibilities.index'));
	}
		/**
	 * Remove the specified Employee from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id) {
		$user = $this->userRepository->findWithoutFail($id);

		if (empty($user)) {
			$user = \App\Models\User::withTrashed()->find($id);
			if($user) {
				$user->employee()->forceDelete();
				$user->forceDelete();
			} 
		} else {
			if($user->employee) {
				$this->employeeRepository->delete($user->employee->id);
			}
			$this->userRepository->delete($id);
		}

		if (empty($user)) {
			Flash::error('User not found');
			return redirect(route('projectresponsibilities.index'));
		}

		Flash::success('Employee deleted successfully.');
		return redirect(route('projectresponsibilities.index'));
	}

	public function getUserDepartments(Request $request){
		$user_id = $request->input('userId');
		$organizationIds = User::findWithoutFail($user_id)->organizations->pluck('id');
		$departments = [];

		foreach($organizationIds as $organizationId){
				
			array_push($departments, Department::where('organization_id','=',$organizationId)->pluck('name'));
		}

		return response()->json(['response' => $departments]);
	}
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
	@include('adminlte-templates::common.errors')
	<div class="card card-primary">
		<div class="card-body">
			{!! Form::open(['route' => 'projectresponsibilities.store', 'files' => true]) !!}
				@include('employees.fields')
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
	@include('adminlte-templates::common.errors')
	<div class="card card-primary">
		<div class="card-body">
			{!! Form::model($user, ['route' => ['projectresponsibilities.update', $user->id], 'method' => 'patch', 'files' => true]) !!}
				@include('employees.fields')
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/employees/fields.blade.php
<div class="row">
	<!-- Name Field -->
	<div class="form-group col-sm-6">
		{!! Form::label('name', 'Name:') !!}
		<div class="name-avatar">
			<div class="avatar">
				<div class="circle">
					<!-- User Profile Image -->
					<img class="profile-pic" src="/assets/images/avatar.png">
				</div>
				<div class="p-image">
					<i class="fa fa-camera upload-button"></i>
					<input class="file-upload" type="file"  name="employee[avatar]" id="profile-img" accept="image/*"/>
				</div>
			</div>

			{!! Form::text('name', null, ['class' => 'form-control']) !!}
		</div>
	</div>

	<!-- Email Field -->
	<div class="form-group col-sm-6">
		{!! Form::label('email', 'Email:') !!}
		{!! Form::email('email', null, ['class' => 'form-control']) !!}
	</div>
</div>
<div class="row">
	<!-- Role Field -->
	<div class="form-group col-sm-6">
		{!! Form::label('roles', 'Role:') !!}
		{!! Form::select('organization[pivot][role_id]', $roles, null, ['class' => 'form-control select2']) !!}
	</div>
	
	<!-- Department Field -->
	<div class="form-group col-sm-6">
		{!! Form::label('department', 'Floor Plan:') !!}
		{!! Form::select('employee[department_id]', $departments, null, ['id' => 'department_field','class' => 'form-control select2', 'multiple' => false]) !!}
	</div>
</div>
<div class="row">
	<!-- Job Title Field -->
	<div class="form-group col-sm-6">
		{!! Form::label('job_title', 'Job Title:') !!}
		{!! Form::text('employee[job_title]', null, ['class' => 'form-control']) !!}
	</div>
	
	<!-- Cost Field -->
	<div class="form-group col-sm-6">
		{!! Form::label('cost', 'Cost per hour:') !!}
		{!! Form::number('employee[cost]', null, ['class' => 'form-control']) !!}
	</div>
</div>

<div class="row">
	<!-- Submit Field -->
	<div class="form-group col-sm-12">
		{!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
		<a href="{!! route('projectresponsibilities.index') !!}" class="btn btn-default">Cancel</a>
	</div>
</div>

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
	@include('flash::message')
	<div class="card card-primary">
		<div class="card-header">
			@if(request()->has('trashed'))
			<a class="btn btn-primary" href="{!! route('projectresponsibilities.index') !!}">
				All
			</a>
			@else
			<a class="btn btn-primary" href="{!! route('projectresponsibilities.create') !!}">
				<i class="fa fa-plus"></i> Add New
			</a>
			<a class="btn btn-primary" href="{!! route('importUsers') !!}">
				<i class="fa fa-plus"></i> Import Users
			</a>
			<a class="btn btn-primary" href="{!! route('exportUsers') !!}">
				<i class="fa fa-plus"></i>Export Users
			</a>
			<a class="btn btn-danger" href="{!! route('projectresponsibilities.index', ['trashed']) !!}">
				<i class="fa fa-trash"></i> Trashed
			</a>
			@endif
		</div>
		<div class="card-body">
			@include('employees.table')
		</div>
		<div class="card-footer">
			@include('vendor.pagination.paginate', ['records' => $users])
		</div>
	</div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="card card-primary">
		<div class="card-body">
			@include('employees.show_fields')
			<a href="{!! route('projectresponsibilities.index') !!}" class="btn btn-default">Back</a>
		</div>
	</div>
@endsection

resources/views/employees/show_fields.blade.php
<div class="row ShowData">
	<div class="pd-30 col-lg-4 col-sm-12 col-xs-12">
		<!-- Avatar Field -->
		<div class="form-group">
			<img id="userAvatar"  src= "{!! $user->employee->avatar !!}" alt="user avatar" width="150px">
		</div>
	</div>

	<div id="userData" class="pd-30 col-lg-8 col-sm-12 col-xs-12">
		<!-- User name Field -->
		<div class="form-group">
			{!! Form::label('name', 'Name:') !!}
			<p>{!! $user->name !!}</p>
		</div>

		<!-- User email Field -->
		<div class="form-group">
			{!! Form::label('email', 'Email:') !!}
			<p>{!! $user->email !!}</p>
		</div>

		<!-- User job title Field -->
		<div class="form-group">
			{!! Form::label('job_title', 'Job Title:') !!}
			<p>{!! $user->employee->job_title !!}</p>
		</div>

		<!-- Department Field -->
		<div class="form-group">
			{!! Form::label('department', 'Floor Plan:') !!}
			<p>{!! $user->employee->department->name !!}</p>
		</div>

		<!-- Cost Field -->
		<div class="form-group">
			{!! Form::label('cost', 'Cost:') !!}
			<p>{!! $user->employee->cost !!}</p>
		</div>
	</div>
</div>

resources/views/employees/table.blade.php
<table class="table table-striped table-hover" id="employees-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($users as $user)
		@if($user->user)
			<?php $user = $user->user ?>
		@endif
		<tr>
			<td>
				{!! $user->name !!}
			</td>
			<td>{!! $user->email !!}</td>
			<td>
				{!! Form::open(['route' => ['projectresponsibilities.destroy', $user->id], 'method' => 'delete']) !!}
					<div class="more-action">
						<div id="more-btn" class="more-btn">
							<span class="more-dot"></span>
							<span class="more-dot"></span>
							<span class="more-dot"></span>
						</div>
						<div class="more-menu">
							<div class="more-menu-caret">
								<div class="more-menu-caret-outer"></div>
								<div class="more-menu-caret-inner"></div>
							</div>
							<ul class="more-menu-items" tabindex="-1" role="menu" aria-labelledby="more-btn" aria-hidden="true">
								@if(request()->has('trashed'))
								<li class="more-menu-item" role="presentation">
									<a href="{!! route('employees.restore', [$user->id]) !!}" class='btn btn-warning btn-sm' title="Restore"><i class="fa fa-refresh"></i></a>
								</li>
								@else
								<li class="more-menu-item" role="presentation">
									<a href="{!! route('projectresponsibilities.show', [$user->id]) !!}" class='btn btn-success btn-sm' title="Show Details"><i class="fa fa-eye"></i></a>
								</li>
								<li class="more-menu-item" role="presentation">
									<a href="{!! route('projectresponsibilities.edit', [$user->id]) !!}"  class='btn btn-info btn-sm' title="Edit"><i class="fa fa-edit"></i></a>
								</li>							
								@endif
								<li class="more-menu-item" role="presentation">
									{!! Form::button('<i class="fa fa-trash"></i>', ['title' => 'Delete','type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Are you sure?')"]) !!}
								</li>						
							</ul>
						</div>
					</div>
				{!! Form::close() !!}				
			</td>
		</tr>
	@endforeach
	</tbody>
</table>