routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/proselect','HomeController@orgselect')->name('orgselect');
Route::post('/proselect','HomeController@orgselect')->name('orgselect');

Route::resource('users', 'UserController');
// Route::resource('permissions', 'PermissionController');
// Route::resource('roles', 'RoleController');
Route::resource('projects', 'OrganizationController');
Route::group(['middleware' => 'orgSelect'], function () {
	Route::get('/home', 'HomeController@index')->name('home');

	
	Route::resource('floorplans', 'DepartmentController');
	
	Route::get('floorplans/{id}/restore', 'DepartmentController@restore')->name('departments.restore');
	Route::resource('projectresponsibilities', 'EmployeeController');
	Route::get('projectresponsibilities/{id}/restore', 'EmployeeController@restore')->name('employees.restore');
	Route::post( '/getUserDepartments', array('as' => 'getUserDepartments', 'uses' => 'EmployeeController@getUserDepartments'));
	
	Route::post('/getOrgUsers', array('as' => 'getOrgUsers', 'uses'=> 'OrganizationController@getOrgUsers'));
	Route::post('/getDepUsers', array('as' => 'getDepUsers', 'uses'=> 'CalendarController@getDepUsers'));
	
	Route::get('/importUsers','UserController@import')->name('importUsers');
	Route::get('/exportUsers','UserController@export')->name('exportUsers');
	Route::get('/downloadEmployeeCsv', 'UserController@getDownload');
	
	// Route::get('/calendars/{id}/approve', array('as' => 'calendars.approve', 'uses'=> 'CalendarController@approve'));
	// Route::get('/calendars/{id}/reject', array('as' => 'calendars.reject', 'uses'=> 'CalendarController@reject'));
	// Route::get('laborcost', 'CostController@index')->name('laborcost');
	// Route::resource('calendars', 'CalendarController');
	// Route::get('calendars/{id}/restore', 'CalendarController@restore')->name('calendars.restore');
	// Route::get('/importCalendars','CalendarController@import')->name('importCalendars');
	// Route::get('/exportCalendars','CalendarController@exportCalendars')->name('exportCalendars');
	// Route::get('/downloadCalendarCsv', 'CalendarController@getDownload');

	
});

// Route::resource('contactForms', 'ContactFormController');
Route::resource('clientdata', 'OrganizationVendorsController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<!-- Twitter -->
	<meta name="twitter:site" content="@bteam.io">
	<meta name="twitter:creator" content="@bteam.io">
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:title" content="BTeam.io">
	<meta name="twitter:description" content="bteam.io">
	<meta name="twitter:image" content="######bteam.io#######">

	<!-- Facebook -->
	<meta property="og:url" content="http://bteam.io">
	<meta property="og:title" content="BTeam.io">
	<meta property="og:description" content="BTeam.io">
	<meta property="og:image" content="######BTeam.io#######">
	<meta property="og:image:secure_url" content="######BTeam.io#######">
	<meta property="og:image:type" content="image/png">
	<meta property="og:image:width" content="1200">
	<meta property="og:image:height" content="600">

	<!-- Meta -->
	<meta name="description" content="BTeam.io">
	<meta name="author" content="momentum-sol">


	<title>BTeam.io Admin</title>

	<!-- vendor css -->
	<link href="{!! url('/lib/font-awesome/css/font-awesome.css') !!}" rel="stylesheet">
	<link href="{!! url('/lib/Ionicons/css/ionicons.css') !!}" rel="stylesheet">
	<link href="{!! url('/lib/bootstrap/css/bootstrap.min.css') !!}" rel="stylesheet">
	<link href="{!! url('/lib/perfect-scrollbar/css/perfect-scrollbar.min.css') !!}" rel="stylesheet">
	<link href="{!! url('/lib/select2/css/select2.min.css') !!}" rel="stylesheet">

	<!-- BTeam.io CSS -->
	<link rel="stylesheet" href="{!! url('/css/slim.css') !!}">
	<link rel="stylesheet" href="{!! url('/css/slim.one.css') !!}">
	<link rel="stylesheet" href="{!! url('/css/buttercup.css') !!}">
	
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
	@yield('css')
</head>

<body>
@if (!Auth::guest())
	@include('layouts.header')

	<div class="slim-body">
		@include('layouts.sidebar')
		<div class="slim-mainpanel">
			<div class="container">
				<div class="slim-pageheader">
					<ol class="breadcrumb slim-breadcrumb">
						{{--  <li class="breadcrumb-item"><a href="/home">Home</a></li>
						<li class="breadcrumb-item active" aria-current="page">{!! Request::segment(1) !!}</li>  --}}
					</ol>
					<h6 class="slim-pagetitle">{!! Request::segment(1) !!}</h6>
				</div><!-- slim-pageheader -->
				@yield('content')
			</div><!-- container -->
	
			<div class="slim-footer mg-t-0">
				<div class="container-fluid">
					<p>Copyright 2019 &copy; All Rights Reserved.</p>
					<p>Powered by <a href="#">Integrated.io</a></p>
				</div><!-- container-fluid -->
			</div><!-- slim-footer -->
		</div><!-- slim-mainpanel -->
	</div>
	
@else
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">

				<!-- Collapsed Hamburger -->
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
						data-target="#app-navbar-collapse">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<!-- Branding Image -->
				<a class="navbar-brand" href="{!! url('/') !!}">
					Buttercup
				</a>
			</div>

			<div class="collapse navbar-collapse" id="app-navbar-collapse">
				<!-- Left Side Of Navbar -->
				<ul class="nav navbar-nav">
					<li><a href="{!! url('/home') !!}">Home</a></li>
				</ul>

				<!-- Right Side Of Navbar -->
				<ul class="nav navbar-nav navbar-right">
					<!-- Authentication Links -->
					<li><a href="{!! url('/login') !!}">Login</a></li>
					<li><a href="{!! url('/register') !!}">Register</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<div id="page-content-wrapper">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					@yield('content')
				</div>
			</div>
		</div>
	</div>
	@endif

	<script src="{!! url('/lib/jquery/js/jquery.js') !!}"></script>
	<script src="{!! url('/lib/jquery-ui/js/jquery-ui.js') !!}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
	<script src="{!! url('/lib/popper.js/js/popper.js') !!}"></script>
	<script src="{!! url('/lib/bootstrap/js/bootstrap.js') !!}"></script>
	<script src="{!! url('/lib/jquery.cookie/js/jquery.cookie.js') !!}"></script>
	<script src="{!! url('/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js') !!}"></script>
	<script src="{!! url('/lib/select2/js/select2.full.min.js') !!}"></script>
	<script src="{!! url('/js/slim.js') !!}"></script>
	<script src="{!! url('/js/buttercup.js') !!}"></script>
	@yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/header.blade.php
<div class="slim-header with-sidebar">
	<div class="container-fluid">
		<div class="slim-header-left">
			<h2 class="slim-logo"><a href="{!! route('home') !!}">{!! Html::image('/assets/images/bteam_whitelogo_full.png', null, ['class' => 'img-fit-cover']) !!}</a></h2>
			<a href="" id="slimSidebarMenu" class="slim-sidebar-menu"><span></span></a>
			<form action="#" method="get" class="search-box">
				<input type="text" name="q" class="form-control" placeholder="Search..."/>
				<button type='submit' class="btn btn-primary">
					<i class="fa fa-search"></i>
				</button>
			</form><!-- search-box -->

		</div><!-- slim-header-left -->
		<div class="slim-header-right">
			{{-- <div class="dropdown dropdown-a" data-toggle="tooltip" title="Activity Logs">
				<a href="" class="header-notification" data-toggle="dropdown">
					<i class="icon ion-ios-bolt-outline"></i>
				</a>
				<div class="dropdown-menu">
					<div class="dropdown-menu-header">
						<h6 class="dropdown-menu-title">Activity Logs</h6>
						<div>
							<a href="">Filter List</a>
							<a href="">Settings</a>
						</div>
					</div><!-- dropdown-menu-header -->
					<div class="dropdown-activity-list">
						<div class="activity-label">Today, December 13, 2017</div>
						<div class="activity-item">
							<div class="row no-gutters">
								<div class="col-2 tx-right">10:15am</div>
								<div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
								<div class="col-8">Purchased christmas sale cloud storage</div>
							</div><!-- row -->
						</div><!-- activity-item -->
						<div class="activity-item">
							<div class="row no-gutters">
								<div class="col-2 tx-right">9:48am</div>
								<div class="col-2 tx-center"><span class="square-10 bg-danger"></span></div>
								<div class="col-8">Login failure</div>
							</div><!-- row -->
						</div><!-- activity-item -->
						<div class="activity-item">
							<div class="row no-gutters">
								<div class="col-2 tx-right">7:29am</div>
								<div class="col-2 tx-center"><span class="square-10 bg-warning"></span></div>
								<div class="col-8">(D:) Storage almost full</div>
							</div><!-- row -->
						</div><!-- activity-item -->
						<div class="activity-item">
							<div class="row no-gutters">
								<div class="col-2 tx-right">3:21am</div>
								<div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
								<div class="col-8">1 item sold <strong>Christmas bundle</strong></div>
							</div><!-- row -->
						</div><!-- activity-item -->
						<div class="activity-label">Yesterday, December 12, 2017</div>
						<div class="activity-item">
							<div class="row no-gutters">
								<div class="col-2 tx-right">6:57am</div>
								<div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
								<div class="col-8">Earn new badge <strong>Elite Author</strong></div>
							</div><!-- row -->
						</div><!-- activity-item -->
					</div><!-- dropdown-activity-list -->
					<div class="dropdown-list-footer">
						<a href="page-activity.html"><i class="fa fa-angle-down"></i> Show All Activities</a>
					</div>
				</div><!-- dropdown-menu-right -->
			</div><!-- dropdown --> --}}
			{{-- <div class="dropdown dropdown-b" data-toggle="tooltip" title="Notifications">
				<a href="" class="header-notification" data-toggle="dropdown">
					<i class="icon ion-ios-bell-outline"></i>
					<span class="indicator"></span>
				</a>
				<div class="dropdown-menu">
					<div class="dropdown-menu-header">
						<h6 class="dropdown-menu-title">Notifications</h6>
						<div>
							<a href="">Mark All as Read</a>
							<a href="">Settings</a>
						</div>
					</div><!-- dropdown-menu-header -->
					<div class="dropdown-list">
						<!-- loop starts here -->
						<a href="" class="dropdown-link">
							<div class="media">
								<img src="http://via.placeholder.com/500x500" alt="">
								<div class="media-body">
									<p><strong>Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
									<span>October 03, 2017 8:45am</span>
								</div>
							</div><!-- media -->
						</a>
						<!-- loop ends here -->
						<a href="" class="dropdown-link">
							<div class="media">
								<img src="http://via.placeholder.com/500x500" alt="">
								<div class="media-body">
									<p><strong>Mellisa Brown</strong> appreciated your work <strong>The Social Network</strong></p>
									<span>October 02, 2017 12:44am</span>
								</div>
							</div><!-- media -->
						</a>
						<a href="" class="dropdown-link read">
							<div class="media">
								<img src="http://via.placeholder.com/500x500" alt="">
								<div class="media-body">
									<p>20+ new items added are for sale in your <strong>Sale Group</strong></p>
									<span>October 01, 2017 10:20pm</span>
								</div>
							</div><!-- media -->
						</a>
						<a href="" class="dropdown-link read">
							<div class="media">
								<img src="http://via.placeholder.com/500x500" alt="">
								<div class="media-body">
									<p><strong>Julius Erving</strong> wants to connect with you on your conversation with <strong>Ronnie Mara</strong></p>
									<span>October 01, 2017 6:08pm</span>
								</div>
							</div><!-- media -->
						</a>
						<div class="dropdown-list-footer">
							<a href="page-notifications.html"><i class="fa fa-angle-down"></i> Show All Notifications</a>
						</div>
					</div><!-- dropdown-list -->
				</div><!-- dropdown-menu-right -->
			</div><!-- dropdown --> --}}
			<div class="dropdown dropdown-c">
				<a href="#" class="logged-user" data-toggle="dropdown">
					<img src="{!! url('/assets/images/logo/logo_square.png') !!}" alt="">
					<span>{!! Auth::user()->name !!}</span>
					<i class="fa fa-angle-down"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-right">
					<nav class="nav">
						{{-- <a href="page-profile.html" class="nav-link"><i class="icon ion-person"></i> View Profile</a>
						<a href="page-edit-profile.html" class="nav-link"><i class="icon ion-compose"></i> Edit Profile</a>
						<a href="page-activity.html" class="nav-link"><i class="icon ion-ios-bolt"></i> Activity Log</a>
						<a href="page-settings.html" class="nav-link"><i class="icon ion-ios-gear"></i> Account Settings</a> --}}
						<a href="{!! route('logout') !!}" class="nav-link"
							onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
							<i class="icon ion-forward"></i> Sign Out
						</a>
						<form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
							{{ csrf_field() }}
						</form>
					</nav>
				</div><!-- dropdown-menu -->
			</div><!-- dropdown -->
		</div><!-- header-right -->
	</div><!-- container-fluid -->
</div><!-- slim-header -->

resources/views/layouts/menu.blade.php
@can('manage-users')
<li class="sidebar-nav-item with-sub">
	<a href="" class="sidebar-nav-link {{ Request::is('users*') || Request::is('permissions*') || Request::is('roles*') ? 'active' : '' }}">
		<i class="fa fa-user"></i>
		<span>User Management</span>
	</a>
	<ul class="nav sidebar-nav-sub">
		<li class="nav-sub-item">
			<a class="nav-sub-link {{ Request::is('users*') ? 'active' : '' }}" href="{!! route('users.index') !!}">Users</a>
		</li>
		{{-- <li class="nav-sub-item">
			<a class="nav-sub-link {{ Request::is('roles*') ? 'active' : '' }}" href="{!! route('roles.index') !!}">Roles</a>
		</li>
		<li class="nav-sub-item">
			<a class="nav-sub-link {{ Request::is('permissions*') ? 'active' : '' }}" href="{!! route('permissions.index') !!}">Permissions</a>
		</li> --}}
	</ul>
</li>
@endcan
<li class="sidebar-nav-item with-sub">
	<a href="" class="sidebar-nav-link {{ Request::is('projects*') || Request::is('floorplans*') || Request::is('projectresponsibilities*') ? 'active' : '' }}">
	<i class="fa fa-building-o"></i>
	<span>Pro Management</span>
	</a>
	<ul class="nav sidebar-nav-sub">
		@can('manage-users')
		<li class="nav-sub-item">
			<a class="nav-sub-link {{ Request::is('projects*') ? 'active' : '' }}" href="{!! route('projects.index') !!}">Projects</a>
		</li>
		@endcan
		<li class="nav-sub-item">
				<a class="nav-sub-link {{ Request::is('floorplans*') ? 'active' : '' }}" href="{!! route('floorplans.index') !!}">Floor Plans</a>
		</li>
		<li class="nav-sub-item">
				<a class="nav-sub-link {{ Request::is('projectresponsibilities*') ? 'active' : '' }}" href="{!! route('projectresponsibilities.index') !!}">Project Responsibilities</a>
		</li>
		<li class="nav-sub-item">
				<a class="nav-sub-link {{ Request::is('clientdata*') ? 'active' : '' }}" href="{!! route('clientdata.index') !!}">Client Data</a>
			</a>
		</li>
	</ul>
</li>

resources/views/layouts/sidebar.blade.php
<div class="slim-sidebar">
	<label class="sidebar-label">
		<a href="{!! route('orgselect') !!}">
			Pro: {!! isset($organization)? $organization->name : '' !!}
		</a>
	</label>
	<ul class="nav nav-sidebar">
		@include('layouts.menu')
	</ul>
</div><!-- slim-sidebar -->