routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/proselect','HomeController@orgselect')->name('orgselect');
Route::post('/proselect','HomeController@orgselect')->name('orgselect');

Route::resource('users', 'UserController');
// Route::resource('permissions', 'PermissionController');
// Route::resource('roles', 'RoleController');
Route::resource('projects', 'OrganizationController');
Route::group(['middleware' => 'orgSelect'], function () {
	Route::get('/home', 'HomeController@index')->name('home');

	
	Route::resource('floorplans', 'DepartmentController');
	
	Route::get('floorplans/{id}/restore', 'DepartmentController@restore')->name('departments.restore');
	Route::resource('projectresponsibilities', 'EmployeeController');
	Route::get('projectresponsibilities/{id}/restore', 'EmployeeController@restore')->name('employees.restore');
	Route::post( '/getUserDepartments', array('as' => 'getUserDepartments', 'uses' => 'EmployeeController@getUserDepartments'));
	
	Route::post('/getOrgUsers', array('as' => 'getOrgUsers', 'uses'=> 'OrganizationController@getOrgUsers'));
	Route::post('/getDepUsers', array('as' => 'getDepUsers', 'uses'=> 'CalendarController@getDepUsers'));
	
	Route::get('/importUsers','UserController@import')->name('importUsers');
	Route::get('/exportUsers','UserController@export')->name('exportUsers');
	Route::get('/downloadEmployeeCsv', 'UserController@getDownload');
	
	// Route::get('/calendars/{id}/approve', array('as' => 'calendars.approve', 'uses'=> 'CalendarController@approve'));
	// Route::get('/calendars/{id}/reject', array('as' => 'calendars.reject', 'uses'=> 'CalendarController@reject'));
	// Route::get('laborcost', 'CostController@index')->name('laborcost');
	// Route::resource('calendars', 'CalendarController');
	// Route::get('calendars/{id}/restore', 'CalendarController@restore')->name('calendars.restore');
	// Route::get('/importCalendars','CalendarController@import')->name('importCalendars');
	// Route::get('/exportCalendars','CalendarController@exportCalendars')->name('exportCalendars');
	// Route::get('/downloadCalendarCsv', 'CalendarController@getDownload');

	
});

// Route::resource('contactForms', 'ContactFormController');
Route::resource('clientdata', 'OrganizationVendorsController');

app/Models/Organization.php
<?php namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Organization
 * @package App\Models
 * @version October 31, 2018, 2:11 pm UTC
 *
  * @property \Illuminate\Database\Eloquent\Collection organizationUsers
 * @property string name
 * @property string logo
 * @property string allowed_domains
 * @property string industry

 */
class Organization extends Model {
	use SoftDeletes;

	public $table = 'organizations';

	protected $dates = ['deleted_at'];

	public $fillable = [
		'name',
		'logo',
		'allowed_domains',
		'industry'
	];

	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'name' => 'string',
		'logo' => 'string',
		'allowed_domains' => 'string',
		'industry' => 'string'
	];

	/**
	 * Validation rules
	 *
	 * @var array
	 */
	public static $rules = [
		'name' => 'required|unique:organizations,name',
		'logo' => 'required|image',
		'industry' => 'required'
	];

	public function setLogoAttribute($file) {
		if (is_file($file)) {
			$file = \Storage::put('public/organizations', $file, 'public');
		}
		$this->attributes['logo'] = $file;
	}

	public function getLogoAttribute($file) {
		$url = '';
		if (\Storage::exists($this->attributes['logo'])) {
			$url = url(\Storage::url($this->attributes['logo']));
		}
		return $url;
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function users() {
		return $this->belongsToMany(\App\Models\User::class, 'organization_users', 'organization_id', 'user_id')->withPivot('role_id');
	}
	
	/**
	 * @return \Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function calendars() {
		return $this->hasMany('App\Models\Calendar', 'organization_id', 'id');
	}
	
	/**
	 * @return \Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function departments() {
		return $this->hasMany('App\Models\Department');
	}
}

app/Http/Controllers/OrganizationController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\CreateOrganizationRequest;
use App\Http\Requests\UpdateOrganizationRequest;
use App\Repositories\OrganizationRepository;
use App\Repositories\UserRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class OrganizationController extends AppBaseController {
	/** @var  OrganizationRepository */
	private $organizationRepository;

	public function __construct(OrganizationRepository $organizationRepo, UserRepository $userRepo) {
		$this->middleware(['verified', 'can:manage-orgs']);
		$this->organizationRepository = $organizationRepo;
		$this->userRepository = $userRepo;
	}

	/**
	 * Display a listing of the Organization.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function index(Request $request) {
		$this->organizationRepository->pushCriteria(new RequestCriteria($request));
		$organizations = $this->organizationRepository->paginate(15);

		return view('organizations.index')
			->with('organizations', $organizations);
	}

	/**
	 * Show the form for creating a new Organization.
	 *
	 * @return Response
	 */
	public function create() {
		$users = $this->userRepository->pluck('name', 'id');
		return view('organizations.create')
					->with('users', $users);
	}

	/**
	 * Store a newly created Organization in storage.
	 *
	 * @param CreateOrganizationRequest $request
	 *
	 * @return Response
	 */
	public function store(CreateOrganizationRequest $request) {
		$input = $request->all();

		$organization = $this->organizationRepository->create($input);

		// $features = ($request->input('features'));
		// $organization->features = json_encode($features);
		// $organization->save();

		// if(in_array('chat',$features)){
		// 	$this->allowChat();
		// }

		// if(in_array('voiceCalls',$features)){
		// 	$this->allowVoiceCalls();
		// }

		// if(in_array('videoCalls',$features)){
		// 	$this->allowVideoCalls();
		// }

		Flash::success('Organization saved successfully.');

		return redirect(route('projects.index'));
	}

	/**
	 * Display the specified Organization.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id) {
		$organization = $this->organizationRepository->findWithoutFail($id);
		$departments = \App\Models\Department::where('organization_id', '=', $id)->get();

		if (empty($organization)) {
			Flash::error('Organization not found');

			return redirect(route('projects.index'));
		}
		// dd($departments);
		return view('organizations.show')->with('organization', $organization)->with('departments', $departments);
	}

	/**
	 * Show the form for editing the specified Organization.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id) {
		$organization = $this->organizationRepository->findWithoutFail($id);
		$users = $this->userRepository->pluck('name', 'id');

		if (empty($organization)) {
			Flash::error('Organization not found');

			return redirect(route('projects.index'));
		}

		return view('organizations.edit')->with('organization', $organization)
			->with('users', $users);
	}

	/**
	 * Update the specified Organization in storage.
	 *
	 * @param  int $id
	 * @param UpdateOrganizationRequest $request
	 *
	 * @return Response
	 */
	public function update($id, UpdateOrganizationRequest $request) {
		$organization = $this->organizationRepository->findWithoutFail($id);

		if (empty($organization)) {
			Flash::error('Organization not found');

			return redirect(route('projects.index'));
		}

		$organization = $this->organizationRepository->update($request->all(), $id);

		$features = ($request->input('features'));
		$organization->features = json_encode($features);
		$organization->save();

		Flash::success('Organization updated successfully.');

		return redirect(route('projects.index'));
	}

	/**
	 * Remove the specified Organization from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id) {
		$organization = $this->organizationRepository->findWithoutFail($id);

		if (empty($organization)) {
			Flash::error('Organization not found');

			return redirect(route('projects.index'));
		}

		$this->organizationRepository->delete($id);

		Flash::success('Organization deleted successfully.');

		return redirect(route('projects.index'));
	}

	public function getOrgUsers(Request $request){
		$orgId = $request->input('orgId');
		if($orgId){
			$orgUsers = \App\Models\Organization::find($orgId)->users()->get()->pluck('name', 'id');
		}
		return response()->json(['response' => $orgUsers]);

	}
	protected function allowChat(){
		//TODO::Create Chat Capability
	}
	protected function allowVoiceCalls(){
		//TODO::Create Voice Calls Capability
	}
	protected function allowVideoCalls(){
		//TODO::Create Video Calls Capability
	}
}

resources/views/organizations/create.blade.php
@extends('layouts.app')

@section('content')
	@include('adminlte-templates::common.errors')
	<div class="card card-primary">
		<div class="card-body">
			{!! Form::open(['route' => 'projects.store', 'files' => true]) !!}
				<div class="row">
					@include('organizations.fields')
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/organizations/edit.blade.php
@extends('layouts.app')

@section('content')
	@include('adminlte-templates::common.errors')
	<div class="card card-primary">
		<div class="card-body">
			{!! Form::model($organization, ['route' => ['projects.update', $organization->id], 'method' => 'patch', 'files' => true]) !!}
				<div class="row">
					@include('organizations.fields')
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/organizations/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
	{!! Form::label('name', 'Name:') !!}
	<div class="name-avatar">
			<div class="avatar">
				<div class="circle">
					<!-- User Profile Image -->
					<img class="profile-pic" src="/assets/images/avatar.png">
				</div>
				<div class="p-image">
					<i class="fa fa-camera upload-button"></i>
					<input class="file-upload" type="file"  name="logo" id="profile-img" accept="image/*"/>
				</div>
			</div>

			{!! Form::text('name', null, ['class' => 'form-control']) !!}
		</div>
</div>

<!-- Logo Field -->
<!-- <div class="form-group col-sm-6">
	{!! Form::label('logo', 'Logo:') !!}
	<div class="custom-file">
		{!! Form::file('logo', ['class' => 'custom-file-input']) !!}
		{!! Form::label('logo', 'Choose Image', ['class' => 'custom-file-label']) !!}
		</div>
</div> -->


<!-- Users Field -->
<div class="form-group col-sm-6">
	{!! Form::label('users', 'Users:') !!}
	{!! Form::select('users[]', $users, null, ['class' => 'form-control select2', 'multiple' => true]) !!}
</div>

<div class="clearfix"></div>


<!-- Industry Field -->
<div class="form-group col-sm-6">
	{!! Form::label('industry', 'Data:') !!}
	{!! Form::textarea('industry', null, ['class' => 'form-control']) !!}
</div>



<!-- Submit Field -->
<div class="form-group col-sm-12">
	{!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
	<a href="{!! route('projects.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/organizations/index.blade.php
@extends('layouts.app')

@section('content')
	@include('flash::message')
	<div class="card card-primary">
		<div class="card-header">
			<a class="btn btn-primary" href="{!! route('projects.create') !!}">
				<i class="fa fa-plus"></i> Add New
			</a>
		</div>
		<div class="card-body">
			@include('organizations.table')
		</div>
		<div class="card-footer">
			@include('vendor.pagination.paginate', ['records' => $organizations])
		</div>
	</div>

@endsection

resources/views/organizations/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="card card-primary">
		<div class="card-body">
			@include('organizations.show_fields')
			<a href="{!! route('projects.index') !!}" class="btn btn-default">Back</a>
		</div>
	</div>
@endsection

resources/views/organizations/show_fields.blade.php
<div class="row pd-20" id="orgContent">
	<div class="col-lg-3">
		<div id="organizationShowLogo">
			<!-- Logo Field -->
			<div class="form-group">
			{{-- {!! Form::label('logo', 'Logo:') !!} --}}
				<img src=" {!! $organization->logo !!}" alt="Organization Logo" srcset="" width="250px" height="250px">
			</div>
		</div>
	</div>
	<div class="col-lg-9 pd-30 ShowData">
		<!-- Name Field -->
		<div class="form-group">
			{!! Form::label('name', 'Name:') !!}
			<p>{!! $organization->name !!}</p>
		</div>
		<!-- Industry Field -->
		<div class="form-group">
			{!! Form::label('industry', 'Data:') !!}
			<p>{!! $organization->industry !!}</p>
		</div>
		<!-- Created At Field -->
		<div class="form-group">
			{!! Form::label('created_at', 'Created At:') !!}
			<p>{!! $organization->created_at !!}</p>
		</div>			
	</div>
</div>
<h3>Floor Plans</h3>
@include('departments.table')

resources/views/organizations/table.blade.php
<table class="table table-striped table-hover" id="organizations-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Logo</th>
			<th>Data</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($organizations as $organization)
		<tr>
			<td>{!! $organization->name !!}</td>
			<td><img width="50" src="{!! $organization->logo !!}" /></td>
			<td>{!! $organization->industry !!}</td>
			<td>
				{!! Form::open(['route' => ['projects.destroy', $organization->id], 'method' => 'delete']) !!}
					<div class="more-action">
						<div id="more-btn" class="more-btn">
							<span class="more-dot"></span>
							<span class="more-dot"></span>
							<span class="more-dot"></span>
						</div>
						<div class="more-menu">
							<div class="more-menu-caret">
								<div class="more-menu-caret-outer"></div>
								<div class="more-menu-caret-inner"></div>
							</div>
							<ul class="more-menu-items" tabindex="-1" role="menu" aria-labelledby="more-btn" aria-hidden="true">
								<li class="more-menu-item" role="presentation">
									<a href="{!! route('projects.show', [$organization->id]) !!}" class='btn btn-success btn-sm' title="Show Details"><i class="fa fa-eye"></i></a>

								</li>
								<li class="more-menu-item" role="presentation">
									<a href="{!! route('projects.edit', [$organization->id]) !!}" class='btn btn-info btn-sm' title="Edit"><i class="fa fa-edit"></i></a>
								</li>
								<li class="more-menu-item" role="presentation">
									{!! Form::button('<i class="fa fa-trash"></i>', ['title' => 'Delete','type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('Are you sure?')"]) !!}
								</li>
							</ul>
						</div>
					</div>
				{!! Form::close() !!}
			</td>
		</tr>
	@endforeach
	</tbody>
</table>