routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/proselect','HomeController@orgselect')->name('orgselect');
Route::post('/proselect','HomeController@orgselect')->name('orgselect');

Route::resource('users', 'UserController');
// Route::resource('permissions', 'PermissionController');
// Route::resource('roles', 'RoleController');
Route::resource('projects', 'OrganizationController');
Route::group(['middleware' => 'orgSelect'], function () {
	Route::get('/home', 'HomeController@index')->name('home');

	
	Route::resource('floorplans', 'DepartmentController');
	
	Route::get('floorplans/{id}/restore', 'DepartmentController@restore')->name('departments.restore');
	Route::resource('projectresponsibilities', 'EmployeeController');
	Route::get('projectresponsibilities/{id}/restore', 'EmployeeController@restore')->name('employees.restore');
	Route::post( '/getUserDepartments', array('as' => 'getUserDepartments', 'uses' => 'EmployeeController@getUserDepartments'));
	
	Route::post('/getOrgUsers', array('as' => 'getOrgUsers', 'uses'=> 'OrganizationController@getOrgUsers'));
	Route::post('/getDepUsers', array('as' => 'getDepUsers', 'uses'=> 'CalendarController@getDepUsers'));
	
	Route::get('/importUsers','UserController@import')->name('importUsers');
	Route::get('/exportUsers','UserController@export')->name('exportUsers');
	Route::get('/downloadEmployeeCsv', 'UserController@getDownload');
	
	// Route::get('/calendars/{id}/approve', array('as' => 'calendars.approve', 'uses'=> 'CalendarController@approve'));
	// Route::get('/calendars/{id}/reject', array('as' => 'calendars.reject', 'uses'=> 'CalendarController@reject'));
	// Route::get('laborcost', 'CostController@index')->name('laborcost');
	// Route::resource('calendars', 'CalendarController');
	// Route::get('calendars/{id}/restore', 'CalendarController@restore')->name('calendars.restore');
	// Route::get('/importCalendars','CalendarController@import')->name('importCalendars');
	// Route::get('/exportCalendars','CalendarController@exportCalendars')->name('exportCalendars');
	// Route::get('/downloadCalendarCsv', 'CalendarController@getDownload');

	
});

// Route::resource('contactForms', 'ContactFormController');
Route::resource('clientdata', 'OrganizationVendorsController');

app/Models/OrganizationVendors.php
<?php namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class OrganizationVendors
 * @package App\Models
 * @version December 26, 2018, 6:38 pm UTC
 *
  * @property string name
 * @property string email
 * @property string phone
 * @property integer organization_id

 */
class OrganizationVendors extends Model {
	    use SoftDeletes;

	public $table = 'organization_vendors';
	
	
    protected $dates = ['deleted_at'];

	
	public $fillable = [
		'name',
        'email',
        'phone',
        'organization_id'
	];

	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'name' => 'string',
        'email' => 'string',
        'phone' => 'string',
        'organization_id' => 'integer'
	];

	/**
	 * Validation rules
	 *
	 * @var array
	 */
	public static $rules = [
		'name' => 'required|unique:organizations,name',
		'phone' => 'required',
		'email' => 'required',
        'organization_id' => 'required'
	];

	
}

app/Http/Controllers/OrganizationVendorsController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\CreateOrganizationVendorsRequest;
use App\Http\Requests\UpdateOrganizationVendorsRequest;
use App\Repositories\OrganizationVendorsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use Auth;

class OrganizationVendorsController extends AppBaseController {
	/** @var  OrganizationVendorsRepository */
	private $organizationVendorsRepository;

	public function __construct(OrganizationVendorsRepository $organizationVendorsRepo) {
		$this->organizationVendorsRepository = $organizationVendorsRepo;
	}

	/**
	 * Display a listing of the OrganizationVendors.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function index(Request $request) {
		$this->organizationVendorsRepository->pushCriteria(new RequestCriteria($request));
		$organizationVendors = $this->organizationVendorsRepository->all();

		return view('organization_vendors.index')
			->with('organizationVendors', $organizationVendors);
	}

	/**
	 * Show the form for creating a new OrganizationVendors.
	 *
	 * @return Response
	 */
	public function create() {
		if(Auth::user()->hasRole(['superadmin', 'admin'])){
			$organizations = \App\Models\Organization::all()->pluck('name', 'id');
		}elseif (Auth::user()->hasRole('orgadmin')){
			$organizations = Auth::user()->organizations->pluck('name', 'id');
		}
		return view('organization_vendors.create')->with('organizations', $organizations);
	}

	/**
	 * Store a newly created OrganizationVendors in storage.
	 *
	 * @param CreateOrganizationVendorsRequest $request
	 *
	 * @return Response
	 */
	public function store(CreateOrganizationVendorsRequest $request) {
		$input = $request->all();

		$organizationVendors = $this->organizationVendorsRepository->create($input);

		Flash::success('Organization Vendors saved successfully.');

		return redirect(route('clientdata.index'));
	}

	/**
	 * Display the specified OrganizationVendors.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id) {
		$organizationVendors = $this->organizationVendorsRepository->findWithoutFail($id);

		if (empty($organizationVendors)) {
			Flash::error('Organization Vendors not found');

			return redirect(route('clientdata.index'));
		}

		return view('organization_vendors.show')->with('organizationVendors', $organizationVendors);
	}

	/**
	 * Show the form for editing the specified OrganizationVendors.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id) {
		$organizationVendors = $this->organizationVendorsRepository->findWithoutFail($id);
		if(Auth::user()->hasRole(['superadmin', 'admin'])){
			$organizations = \App\Models\Organization::all()->pluck('name', 'id');
		}elseif (Auth::user()->hasRole('orgadmin')){
			$organizations = Auth::user()->organizations->pluck('name', 'id');
		}
		if (empty($organizationVendors)) {
			Flash::error('Organization Vendors not found');

			return redirect(route('clientdata.index'));
		}

		return view('organization_vendors.edit')->with('organizationVendors', $organizationVendors)->with('organizations',$organizations);
	}

	/**
	 * Update the specified OrganizationVendors in storage.
	 *
	 * @param  int			  $id
	 * @param UpdateOrganizationVendorsRequest $request
	 *
	 * @return Response
	 */
	public function update($id, UpdateOrganizationVendorsRequest $request) {
		$organizationVendors = $this->organizationVendorsRepository->findWithoutFail($id);

		if (empty($organizationVendors)) {
			Flash::error('Organization Vendors not found');

			return redirect(route('clientdata.index'));
		}

		$organizationVendors = $this->organizationVendorsRepository->update($request->all(), $id);

		Flash::success('Organization Vendors updated successfully.');

		return redirect(route('clientdata.index'));
	}

	/**
	 * Remove the specified OrganizationVendors from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id) {
		$organizationVendors = $this->organizationVendorsRepository->findWithoutFail($id);

		if (empty($organizationVendors)) {
			Flash::error('Organization Vendors not found');

			return redirect(route('clientdata.index'));
		}

		$this->organizationVendorsRepository->delete($id);

		Flash::success('Organization Vendors deleted successfully.');

		return redirect(route('clientdata.index'));
	}
}

resources/views/organization_vendors/create.blade.php
@extends('layouts.app')

@section('content')
	@include('adminlte-templates::common.errors')
	<div class="card card-primary">
		<div class="card-body">
			{!! Form::open(['route' => 'clientdata.store', 'files' => true]) !!}
				@include('organization_vendors.fields')
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/organization_vendors/edit.blade.php
@extends('layouts.app')

@section('content')
	@include('adminlte-templates::common.errors')
	<div class="card card-primary">
		<div class="card-body">
			{!! Form::model($organizationVendors, ['route' => ['clientdata.update', $organizationVendors->id], 'method' => 'patch', 'files' => true]) !!}
				@include('organization_vendors.fields')
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/organization_vendors/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
	{!! Form::label('name', 'Name:') !!}
	{!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
	{!! Form::label('email', 'Email:') !!}
	{!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
	{!! Form::label('phone', 'Phone:') !!}
	{!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Organization Id Field -->
<div class="form-group col-sm-6">
	{!! Form::label('organization_id', 'Project:') !!}
	{!! Form::select('organization_id', $organizations, null, ['id' => 'organization_id','class' => 'form-control select2', 'multiple' => false]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
	{!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
	<a href="{!! route('clientdata.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/organization_vendors/index.blade.php
@extends('layouts.app')

@section('content')
	@include('flash::message')
	<div class="card card-primary">
		<div class="card-header">
			<a class="btn btn-primary" href="{!! route('clientdata.create') !!}">
				<i class="fa fa-plus"></i> Add New
			</a>
		</div>
		<div class="card-body">
			@include('organization_vendors.table')
		</div>
	</div>
	<div class="text-center">
		
	</div>
@endsection

resources/views/organization_vendors/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="card card-primary">
		<div class="card-body">
			@include('organization_vendors.show_fields')
			<a href="{!! route('clientdata.index') !!}" class="btn btn-default">Back</a>
		</div>
	</div>
@endsection

resources/views/organization_vendors/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
	{!! Form::label('id', 'Id:') !!}
	<p>{!! $organizationVendors->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
	{!! Form::label('name', 'Name:') !!}
	<p>{!! $organizationVendors->name !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
	{!! Form::label('email', 'Email:') !!}
	<p>{!! $organizationVendors->email !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
	{!! Form::label('phone', 'Phone:') !!}
	<p>{!! $organizationVendors->phone !!}</p>
</div>

<!-- Organization Id Field -->
<div class="form-group">
	{!! Form::label('organization_id', 'Project Id:') !!}
	<p>{!! $organizationVendors->organization_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
	{!! Form::label('created_at', 'Created At:') !!}
	<p>{!! $organizationVendors->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
	{!! Form::label('updated_at', 'Updated At:') !!}
	<p>{!! $organizationVendors->updated_at !!}</p>
</div>

resources/views/organization_vendors/table.blade.php
<table class="table table-striped table-hover" id="organizationVendors-table">
	<thead>
		<tr>
			<th>Name</th>
       		<th>Email</th>
			<th>Phone</th>
			<th>Project Id</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($organizationVendors as $organizationVendors)
		<tr>
			<td>{!! $organizationVendors->name !!}</td>
            <td>{!! $organizationVendors->email !!}</td>
            <td>{!! $organizationVendors->phone !!}</td>
            <td>{!! \App\Models\Organization::find($organizationVendors->organization_id)->name !!}</td>
			<td>
				{!! Form::open(['route' => ['clientdata.destroy', $organizationVendors->id], 'method' => 'delete']) !!}
				<div class='btn-group'>
					<a href="{!! route('clientdata.show', [$organizationVendors->id]) !!}" class='btn btn-success btn-xs'><i class="fa fa-eye"></i></a>
					<a href="{!! route('clientdata.edit', [$organizationVendors->id]) !!}" class='btn btn-info btn-xs'><i class="fa fa-edit"></i></a>
					{!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
				</div>
				{!! Form::close() !!}
			</td>
		</tr>
	@endforeach
	</tbody>
</table>